// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_keys.sql

package store

import (
	"context"
)

const createAPIKey = `-- name: CreateAPIKey :exec
INSERT INTO api_keys (id, user_id, name, key_hash, enabled, expires_at, created_at, updated_at)
VALUES (?, ?, ?, ?, 1, ?, ?, ?)
`

type CreateAPIKeyParams struct {
	ID        string
	UserID    string
	Name      string
	KeyHash   string
	ExpiresAt *int64
	CreatedAt int64
	UpdatedAt int64
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) error {
	_, err := q.db.ExecContext(ctx, createAPIKey,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.KeyHash,
		arg.ExpiresAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteAPIKey = `-- name: DeleteAPIKey :exec
DELETE FROM api_keys WHERE id = ? AND user_id = ?
`

type DeleteAPIKeyParams struct {
	ID     string
	UserID string
}

func (q *Queries) DeleteAPIKey(ctx context.Context, arg DeleteAPIKeyParams) error {
	_, err := q.db.ExecContext(ctx, deleteAPIKey, arg.ID, arg.UserID)
	return err
}

const getAPIKeyByHash = `-- name: GetAPIKeyByHash :one
SELECT id, user_id, name, key_hash, enabled, expires_at, request_count, last_request_at, rate_limit_max, rate_limit_window, created_at, updated_at FROM api_keys WHERE key_hash = ?
`

func (q *Queries) GetAPIKeyByHash(ctx context.Context, keyHash string) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, getAPIKeyByHash, keyHash)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.KeyHash,
		&i.Enabled,
		&i.ExpiresAt,
		&i.RequestCount,
		&i.LastRequestAt,
		&i.RateLimitMax,
		&i.RateLimitWindow,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAPIKeysByUser = `-- name: ListAPIKeysByUser :many
SELECT id, user_id, name, key_hash, enabled, expires_at, request_count, last_request_at, rate_limit_max, rate_limit_window, created_at, updated_at FROM api_keys WHERE user_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListAPIKeysByUser(ctx context.Context, userID string) ([]ApiKey, error) {
	rows, err := q.db.QueryContext(ctx, listAPIKeysByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApiKey
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.KeyHash,
			&i.Enabled,
			&i.ExpiresAt,
			&i.RequestCount,
			&i.LastRequestAt,
			&i.RateLimitMax,
			&i.RateLimitWindow,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAPIKeyRateLimit = `-- name: UpdateAPIKeyRateLimit :execrows
UPDATE api_keys
SET request_count = CASE
        WHEN last_request_at IS NULL OR last_request_at < ?1 THEN 1
        ELSE request_count + 1
    END,
    last_request_at = ?2
WHERE id = ?3
  AND (
    request_count < ?4 OR last_request_at IS NULL OR last_request_at < ?1
  )
`

type UpdateAPIKeyRateLimitParams struct {
	WindowStart *int64
	Now         *int64
	ID          string
	Max         int64
}

func (q *Queries) UpdateAPIKeyRateLimit(ctx context.Context, arg UpdateAPIKeyRateLimitParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateAPIKeyRateLimit,
		arg.WindowStart,
		arg.Now,
		arg.ID,
		arg.Max,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
