// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: credentials.sql

package store

import (
	"context"
)

const getCredential = `-- name: GetCredential :one
SELECT user_id, password_hash, updated_at FROM credentials WHERE user_id = ?
`

func (q *Queries) GetCredential(ctx context.Context, userID string) (Credential, error) {
	row := q.db.QueryRowContext(ctx, getCredential, userID)
	var i Credential
	err := row.Scan(&i.UserID, &i.PasswordHash, &i.UpdatedAt)
	return i, err
}

const upsertCredential = `-- name: UpsertCredential :exec
INSERT INTO credentials (user_id, password_hash, updated_at)
VALUES (?, ?, ?)
ON CONFLICT (user_id) DO UPDATE
SET password_hash = excluded.password_hash,
    updated_at = excluded.updated_at
`

type UpsertCredentialParams struct {
	UserID       string
	PasswordHash string
	UpdatedAt    int64
}

func (q *Queries) UpsertCredential(ctx context.Context, arg UpsertCredentialParams) error {
	_, err := q.db.ExecContext(ctx, upsertCredential, arg.UserID, arg.PasswordHash, arg.UpdatedAt)
	return err
}
