// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

type ApiKey struct {
	ID              string
	UserID          string
	Name            string
	KeyHash         string
	Enabled         bool
	ExpiresAt       *int64
	RequestCount    int64
	LastRequestAt   *int64
	RateLimitMax    int64
	RateLimitWindow int64
	CreatedAt       int64
	UpdatedAt       int64
}

type Credential struct {
	UserID       string
	PasswordHash string
	UpdatedAt    int64
}

type OauthAccount struct {
	ID             string
	UserID         string
	ProviderID     string
	ProviderUserID string
	Email          string
	CreatedAt      int64
}

type Passkey struct {
	ID           string
	UserID       string
	Name         string
	CredentialID string
	PublicKey    []byte
	Counter      int64
	Aaguid       []byte
	Transports   string
	CreatedAt    int64
}

type ResetToken struct {
	ID        string
	UserID    string
	TokenHash string
	ExpiresAt int64
	CreatedAt int64
}

type Session struct {
	ID             string
	UserID         string
	TokenHash      string
	ExpiresAt      int64
	IpAddress      string
	UserAgent      string
	ImpersonatedBy *string
	CreatedAt      int64
}

type User struct {
	ID            string
	Name          string
	Email         string
	EmailVerified bool
	Username      *string
	Avatar        string
	Role          string
	CreatedAt     int64
	UpdatedAt     int64
}

type WebauthnChallenge struct {
	ID        string
	Challenge string
	UserID    *string
	Kind      string
	ExpiresAt int64
	CreatedAt int64
}
