// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: oauth_accounts.sql

package store

import (
	"context"
)

const getOAuthAccountUser = `-- name: GetOAuthAccountUser :one
SELECT user_id FROM oauth_accounts WHERE provider_id = ? AND provider_user_id = ?
`

type GetOAuthAccountUserParams struct {
	ProviderID     string
	ProviderUserID string
}

func (q *Queries) GetOAuthAccountUser(ctx context.Context, arg GetOAuthAccountUserParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getOAuthAccountUser, arg.ProviderID, arg.ProviderUserID)
	var user_id string
	err := row.Scan(&user_id)
	return user_id, err
}

const insertOAuthAccount = `-- name: InsertOAuthAccount :exec
INSERT INTO oauth_accounts (id, user_id, provider_id, provider_user_id, email, created_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertOAuthAccountParams struct {
	ID             string
	UserID         string
	ProviderID     string
	ProviderUserID string
	Email          string
	CreatedAt      int64
}

func (q *Queries) InsertOAuthAccount(ctx context.Context, arg InsertOAuthAccountParams) error {
	_, err := q.db.ExecContext(ctx, insertOAuthAccount,
		arg.ID,
		arg.UserID,
		arg.ProviderID,
		arg.ProviderUserID,
		arg.Email,
		arg.CreatedAt,
	)
	return err
}
