// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: passkeys.sql

package store

import (
	"context"
)

const deletePasskey = `-- name: DeletePasskey :exec
DELETE FROM passkeys WHERE id = ? AND user_id = ?
`

type DeletePasskeyParams struct {
	ID     string
	UserID string
}

func (q *Queries) DeletePasskey(ctx context.Context, arg DeletePasskeyParams) error {
	_, err := q.db.ExecContext(ctx, deletePasskey, arg.ID, arg.UserID)
	return err
}

const insertPasskey = `-- name: InsertPasskey :exec
INSERT INTO passkeys (id, user_id, name, credential_id, public_key, counter, aaguid, transports, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertPasskeyParams struct {
	ID           string
	UserID       string
	Name         string
	CredentialID string
	PublicKey    []byte
	Counter      int64
	Aaguid       []byte
	Transports   string
	CreatedAt    int64
}

func (q *Queries) InsertPasskey(ctx context.Context, arg InsertPasskeyParams) error {
	_, err := q.db.ExecContext(ctx, insertPasskey,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.CredentialID,
		arg.PublicKey,
		arg.Counter,
		arg.Aaguid,
		arg.Transports,
		arg.CreatedAt,
	)
	return err
}

const listPasskeyPublicKeys = `-- name: ListPasskeyPublicKeys :many
SELECT public_key FROM passkeys WHERE user_id = ?
`

func (q *Queries) ListPasskeyPublicKeys(ctx context.Context, userID string) ([][]byte, error) {
	rows, err := q.db.QueryContext(ctx, listPasskeyPublicKeys, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items [][]byte
	for rows.Next() {
		var public_key []byte
		if err := rows.Scan(&public_key); err != nil {
			return nil, err
		}
		items = append(items, public_key)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPasskeysByUser = `-- name: ListPasskeysByUser :many
SELECT id, user_id, name, credential_id, created_at FROM passkeys WHERE user_id = ?
`

type ListPasskeysByUserRow struct {
	ID           string
	UserID       string
	Name         string
	CredentialID string
	CreatedAt    int64
}

func (q *Queries) ListPasskeysByUser(ctx context.Context, userID string) ([]ListPasskeysByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listPasskeysByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPasskeysByUserRow
	for rows.Next() {
		var i ListPasskeysByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.CredentialID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePasskeyCounter = `-- name: UpdatePasskeyCounter :exec
UPDATE passkeys SET counter = ? WHERE user_id = ? AND credential_id = ?
`

type UpdatePasskeyCounterParams struct {
	Counter      int64
	UserID       string
	CredentialID string
}

func (q *Queries) UpdatePasskeyCounter(ctx context.Context, arg UpdatePasskeyCounterParams) error {
	_, err := q.db.ExecContext(ctx, updatePasskeyCounter, arg.Counter, arg.UserID, arg.CredentialID)
	return err
}
