// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reset_tokens.sql

package store

import (
	"context"
)

const deleteResetTokensByUser = `-- name: DeleteResetTokensByUser :exec
DELETE FROM reset_tokens WHERE user_id = ?
`

func (q *Queries) DeleteResetTokensByUser(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteResetTokensByUser, userID)
	return err
}

const getActiveResetToken = `-- name: GetActiveResetToken :one
SELECT user_id FROM reset_tokens WHERE token_hash = ? AND expires_at > ?
`

type GetActiveResetTokenParams struct {
	TokenHash string
	ExpiresAt int64
}

func (q *Queries) GetActiveResetToken(ctx context.Context, arg GetActiveResetTokenParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getActiveResetToken, arg.TokenHash, arg.ExpiresAt)
	var user_id string
	err := row.Scan(&user_id)
	return user_id, err
}

const insertResetToken = `-- name: InsertResetToken :exec
INSERT INTO reset_tokens (id, user_id, token_hash, expires_at, created_at)
VALUES (?, ?, ?, ?, ?)
`

type InsertResetTokenParams struct {
	ID        string
	UserID    string
	TokenHash string
	ExpiresAt int64
	CreatedAt int64
}

func (q *Queries) InsertResetToken(ctx context.Context, arg InsertResetTokenParams) error {
	_, err := q.db.ExecContext(ctx, insertResetToken,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}
