// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package store

import (
	"context"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (id, user_id, token_hash, expires_at, ip_address, user_agent, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateSessionParams struct {
	ID        string
	UserID    string
	TokenHash string
	ExpiresAt int64
	IpAddress string
	UserAgent string
	CreatedAt int64
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.IpAddress,
		arg.UserAgent,
		arg.CreatedAt,
	)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at < ?
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context, expiresAt int64) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredSessions, expiresAt)
	return err
}

const deleteOtherSessions = `-- name: DeleteOtherSessions :exec
DELETE FROM sessions WHERE user_id = ? AND id != ?
`

type DeleteOtherSessionsParams struct {
	UserID string
	ID     string
}

func (q *Queries) DeleteOtherSessions(ctx context.Context, arg DeleteOtherSessionsParams) error {
	_, err := q.db.ExecContext(ctx, deleteOtherSessions, arg.UserID, arg.ID)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = ? AND user_id = ?
`

type DeleteSessionParams struct {
	ID     string
	UserID string
}

func (q *Queries) DeleteSession(ctx context.Context, arg DeleteSessionParams) error {
	_, err := q.db.ExecContext(ctx, deleteSession, arg.ID, arg.UserID)
	return err
}

const deleteSessionByTokenHash = `-- name: DeleteSessionByTokenHash :exec
DELETE FROM sessions WHERE token_hash = ?
`

func (q *Queries) DeleteSessionByTokenHash(ctx context.Context, tokenHash string) error {
	_, err := q.db.ExecContext(ctx, deleteSessionByTokenHash, tokenHash)
	return err
}

const deleteSessionsByUser = `-- name: DeleteSessionsByUser :exec
DELETE FROM sessions WHERE user_id = ?
`

func (q *Queries) DeleteSessionsByUser(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteSessionsByUser, userID)
	return err
}

const getSessionWithUserByTokenHash = `-- name: GetSessionWithUserByTokenHash :one
SELECT
    s.id AS session_id,
    s.user_id AS session_user_id,
    s.expires_at,
    s.ip_address,
    s.user_agent,
    s.impersonated_by,
    s.created_at AS session_created_at,
    u.id AS user_id,
    u.name AS user_name,
    u.email AS user_email,
    u.email_verified AS user_email_verified,
    u.username AS user_username,
    u.avatar AS user_avatar,
    u.role AS user_role,
    u.created_at AS user_created_at,
    u.updated_at AS user_updated_at
FROM sessions s
JOIN users u ON u.id = s.user_id
WHERE s.token_hash = ?
`

type GetSessionWithUserByTokenHashRow struct {
	SessionID         string
	SessionUserID     string
	ExpiresAt         int64
	IpAddress         string
	UserAgent         string
	ImpersonatedBy    *string
	SessionCreatedAt  int64
	UserID            string
	UserName          string
	UserEmail         string
	UserEmailVerified bool
	UserUsername      *string
	UserAvatar        string
	UserRole          string
	UserCreatedAt     int64
	UserUpdatedAt     int64
}

func (q *Queries) GetSessionWithUserByTokenHash(ctx context.Context, tokenHash string) (GetSessionWithUserByTokenHashRow, error) {
	row := q.db.QueryRowContext(ctx, getSessionWithUserByTokenHash, tokenHash)
	var i GetSessionWithUserByTokenHashRow
	err := row.Scan(
		&i.SessionID,
		&i.SessionUserID,
		&i.ExpiresAt,
		&i.IpAddress,
		&i.UserAgent,
		&i.ImpersonatedBy,
		&i.SessionCreatedAt,
		&i.UserID,
		&i.UserName,
		&i.UserEmail,
		&i.UserEmailVerified,
		&i.UserUsername,
		&i.UserAvatar,
		&i.UserRole,
		&i.UserCreatedAt,
		&i.UserUpdatedAt,
	)
	return i, err
}

const listSessionsByUser = `-- name: ListSessionsByUser :many
SELECT id, user_id, expires_at, ip_address, user_agent, impersonated_by, created_at
FROM sessions
WHERE user_id = ?
ORDER BY created_at DESC
`

type ListSessionsByUserRow struct {
	ID             string
	UserID         string
	ExpiresAt      int64
	IpAddress      string
	UserAgent      string
	ImpersonatedBy *string
	CreatedAt      int64
}

func (q *Queries) ListSessionsByUser(ctx context.Context, userID string) ([]ListSessionsByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listSessionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSessionsByUserRow
	for rows.Next() {
		var i ListSessionsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ExpiresAt,
			&i.IpAddress,
			&i.UserAgent,
			&i.ImpersonatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
