// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webauthn_challenges.sql

package store

import (
	"context"
)

const deleteChallenge = `-- name: DeleteChallenge :exec
DELETE FROM webauthn_challenges WHERE id = ?
`

func (q *Queries) DeleteChallenge(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteChallenge, id)
	return err
}

const getChallenge = `-- name: GetChallenge :one
SELECT challenge, user_id FROM webauthn_challenges
WHERE id = ? AND kind = ? AND expires_at > ?
`

type GetChallengeParams struct {
	ID        string
	Kind      string
	ExpiresAt int64
}

type GetChallengeRow struct {
	Challenge string
	UserID    *string
}

func (q *Queries) GetChallenge(ctx context.Context, arg GetChallengeParams) (GetChallengeRow, error) {
	row := q.db.QueryRowContext(ctx, getChallenge, arg.ID, arg.Kind, arg.ExpiresAt)
	var i GetChallengeRow
	err := row.Scan(&i.Challenge, &i.UserID)
	return i, err
}

const insertChallenge = `-- name: InsertChallenge :exec
INSERT INTO webauthn_challenges (id, challenge, user_id, kind, expires_at, created_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertChallengeParams struct {
	ID        string
	Challenge string
	UserID    *string
	Kind      string
	ExpiresAt int64
	CreatedAt int64
}

func (q *Queries) InsertChallenge(ctx context.Context, arg InsertChallengeParams) error {
	_, err := q.db.ExecContext(ctx, insertChallenge,
		arg.ID,
		arg.Challenge,
		arg.UserID,
		arg.Kind,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}
