/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivateRouteRouteImport } from './routes/_private/route'
import { Route as PrivateIndexRouteImport } from './routes/_private/index'
import { Route as AuthPathRouteImport } from './routes/auth/$path'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as PrivateVolumesRouteImport } from './routes/_private/volumes'
import { Route as PrivateNetworksRouteImport } from './routes/_private/networks'
import { Route as PrivateImagesRouteImport } from './routes/_private/images'
import { Route as PrivateContainersRouteImport } from './routes/_private/containers'
import { Route as ApiStacksIndexRouteImport } from './routes/api/stacks/index'
import { Route as ApiWsLogsRouteImport } from './routes/api/ws/logs'
import { Route as ApiWsExecRouteImport } from './routes/api/ws/exec'
import { Route as ApiStacksRedeployRouteImport } from './routes/api/stacks/redeploy'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as PrivateStacksNameRouteImport } from './routes/_private/stacks.$name'
import { Route as PrivateSettingsPathRouteImport } from './routes/_private/settings/$path'

const PrivateRouteRoute = PrivateRouteRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateIndexRoute = PrivateIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const AuthPathRoute = AuthPathRouteImport.update({
  id: '/auth/$path',
  path: '/auth/$path',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateVolumesRoute = PrivateVolumesRouteImport.update({
  id: '/volumes',
  path: '/volumes',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateNetworksRoute = PrivateNetworksRouteImport.update({
  id: '/networks',
  path: '/networks',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateImagesRoute = PrivateImagesRouteImport.update({
  id: '/images',
  path: '/images',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateContainersRoute = PrivateContainersRouteImport.update({
  id: '/containers',
  path: '/containers',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const ApiStacksIndexRoute = ApiStacksIndexRouteImport.update({
  id: '/api/stacks/',
  path: '/api/stacks/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWsLogsRoute = ApiWsLogsRouteImport.update({
  id: '/api/ws/logs',
  path: '/api/ws/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWsExecRoute = ApiWsExecRouteImport.update({
  id: '/api/ws/exec',
  path: '/api/ws/exec',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStacksRedeployRoute = ApiStacksRedeployRouteImport.update({
  id: '/api/stacks/redeploy',
  path: '/api/stacks/redeploy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateStacksNameRoute = PrivateStacksNameRouteImport.update({
  id: '/stacks/$name',
  path: '/stacks/$name',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateSettingsPathRoute = PrivateSettingsPathRouteImport.update({
  id: '/settings/$path',
  path: '/settings/$path',
  getParentRoute: () => PrivateRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PrivateIndexRoute
  '/containers': typeof PrivateContainersRoute
  '/images': typeof PrivateImagesRoute
  '/networks': typeof PrivateNetworksRoute
  '/volumes': typeof PrivateVolumesRoute
  '/api/health': typeof ApiHealthRoute
  '/auth/$path': typeof AuthPathRoute
  '/settings/$path': typeof PrivateSettingsPathRoute
  '/stacks/$name': typeof PrivateStacksNameRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/stacks/redeploy': typeof ApiStacksRedeployRoute
  '/api/ws/exec': typeof ApiWsExecRoute
  '/api/ws/logs': typeof ApiWsLogsRoute
  '/api/stacks/': typeof ApiStacksIndexRoute
}
export interface FileRoutesByTo {
  '/containers': typeof PrivateContainersRoute
  '/images': typeof PrivateImagesRoute
  '/networks': typeof PrivateNetworksRoute
  '/volumes': typeof PrivateVolumesRoute
  '/api/health': typeof ApiHealthRoute
  '/auth/$path': typeof AuthPathRoute
  '/': typeof PrivateIndexRoute
  '/settings/$path': typeof PrivateSettingsPathRoute
  '/stacks/$name': typeof PrivateStacksNameRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/stacks/redeploy': typeof ApiStacksRedeployRoute
  '/api/ws/exec': typeof ApiWsExecRoute
  '/api/ws/logs': typeof ApiWsLogsRoute
  '/api/stacks': typeof ApiStacksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_private': typeof PrivateRouteRouteWithChildren
  '/_private/containers': typeof PrivateContainersRoute
  '/_private/images': typeof PrivateImagesRoute
  '/_private/networks': typeof PrivateNetworksRoute
  '/_private/volumes': typeof PrivateVolumesRoute
  '/api/health': typeof ApiHealthRoute
  '/auth/$path': typeof AuthPathRoute
  '/_private/': typeof PrivateIndexRoute
  '/_private/settings/$path': typeof PrivateSettingsPathRoute
  '/_private/stacks/$name': typeof PrivateStacksNameRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/stacks/redeploy': typeof ApiStacksRedeployRoute
  '/api/ws/exec': typeof ApiWsExecRoute
  '/api/ws/logs': typeof ApiWsLogsRoute
  '/api/stacks/': typeof ApiStacksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/containers'
    | '/images'
    | '/networks'
    | '/volumes'
    | '/api/health'
    | '/auth/$path'
    | '/settings/$path'
    | '/stacks/$name'
    | '/api/auth/$'
    | '/api/stacks/redeploy'
    | '/api/ws/exec'
    | '/api/ws/logs'
    | '/api/stacks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/containers'
    | '/images'
    | '/networks'
    | '/volumes'
    | '/api/health'
    | '/auth/$path'
    | '/'
    | '/settings/$path'
    | '/stacks/$name'
    | '/api/auth/$'
    | '/api/stacks/redeploy'
    | '/api/ws/exec'
    | '/api/ws/logs'
    | '/api/stacks'
  id:
    | '__root__'
    | '/_private'
    | '/_private/containers'
    | '/_private/images'
    | '/_private/networks'
    | '/_private/volumes'
    | '/api/health'
    | '/auth/$path'
    | '/_private/'
    | '/_private/settings/$path'
    | '/_private/stacks/$name'
    | '/api/auth/$'
    | '/api/stacks/redeploy'
    | '/api/ws/exec'
    | '/api/ws/logs'
    | '/api/stacks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PrivateRouteRoute: typeof PrivateRouteRouteWithChildren
  ApiHealthRoute: typeof ApiHealthRoute
  AuthPathRoute: typeof AuthPathRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiStacksRedeployRoute: typeof ApiStacksRedeployRoute
  ApiWsExecRoute: typeof ApiWsExecRoute
  ApiWsLogsRoute: typeof ApiWsLogsRoute
  ApiStacksIndexRoute: typeof ApiStacksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PrivateRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/': {
      id: '/_private/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PrivateIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/auth/$path': {
      id: '/auth/$path'
      path: '/auth/$path'
      fullPath: '/auth/$path'
      preLoaderRoute: typeof AuthPathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/volumes': {
      id: '/_private/volumes'
      path: '/volumes'
      fullPath: '/volumes'
      preLoaderRoute: typeof PrivateVolumesRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/networks': {
      id: '/_private/networks'
      path: '/networks'
      fullPath: '/networks'
      preLoaderRoute: typeof PrivateNetworksRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/images': {
      id: '/_private/images'
      path: '/images'
      fullPath: '/images'
      preLoaderRoute: typeof PrivateImagesRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/containers': {
      id: '/_private/containers'
      path: '/containers'
      fullPath: '/containers'
      preLoaderRoute: typeof PrivateContainersRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/api/stacks/': {
      id: '/api/stacks/'
      path: '/api/stacks'
      fullPath: '/api/stacks/'
      preLoaderRoute: typeof ApiStacksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ws/logs': {
      id: '/api/ws/logs'
      path: '/api/ws/logs'
      fullPath: '/api/ws/logs'
      preLoaderRoute: typeof ApiWsLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ws/exec': {
      id: '/api/ws/exec'
      path: '/api/ws/exec'
      fullPath: '/api/ws/exec'
      preLoaderRoute: typeof ApiWsExecRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stacks/redeploy': {
      id: '/api/stacks/redeploy'
      path: '/api/stacks/redeploy'
      fullPath: '/api/stacks/redeploy'
      preLoaderRoute: typeof ApiStacksRedeployRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/stacks/$name': {
      id: '/_private/stacks/$name'
      path: '/stacks/$name'
      fullPath: '/stacks/$name'
      preLoaderRoute: typeof PrivateStacksNameRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/settings/$path': {
      id: '/_private/settings/$path'
      path: '/settings/$path'
      fullPath: '/settings/$path'
      preLoaderRoute: typeof PrivateSettingsPathRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
  }
}

interface PrivateRouteRouteChildren {
  PrivateContainersRoute: typeof PrivateContainersRoute
  PrivateImagesRoute: typeof PrivateImagesRoute
  PrivateNetworksRoute: typeof PrivateNetworksRoute
  PrivateVolumesRoute: typeof PrivateVolumesRoute
  PrivateIndexRoute: typeof PrivateIndexRoute
  PrivateSettingsPathRoute: typeof PrivateSettingsPathRoute
  PrivateStacksNameRoute: typeof PrivateStacksNameRoute
}

const PrivateRouteRouteChildren: PrivateRouteRouteChildren = {
  PrivateContainersRoute: PrivateContainersRoute,
  PrivateImagesRoute: PrivateImagesRoute,
  PrivateNetworksRoute: PrivateNetworksRoute,
  PrivateVolumesRoute: PrivateVolumesRoute,
  PrivateIndexRoute: PrivateIndexRoute,
  PrivateSettingsPathRoute: PrivateSettingsPathRoute,
  PrivateStacksNameRoute: PrivateStacksNameRoute,
}

const PrivateRouteRouteWithChildren = PrivateRouteRoute._addFileChildren(
  PrivateRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PrivateRouteRoute: PrivateRouteRouteWithChildren,
  ApiHealthRoute: ApiHealthRoute,
  AuthPathRoute: AuthPathRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiStacksRedeployRoute: ApiStacksRedeployRoute,
  ApiWsExecRoute: ApiWsExecRoute,
  ApiWsLogsRoute: ApiWsLogsRoute,
  ApiStacksIndexRoute: ApiStacksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
