/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StacksNameRouteImport } from './routes/stacks.$name'
import { Route as SettingsPathRouteImport } from './routes/settings/$path'
import { Route as AuthPathRouteImport } from './routes/auth/$path'
import { Route as ApiStacksRedeployRouteImport } from './routes/api/stacks/redeploy'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StacksNameRoute = StacksNameRouteImport.update({
  id: '/stacks/$name',
  path: '/stacks/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsPathRoute = SettingsPathRouteImport.update({
  id: '/settings/$path',
  path: '/settings/$path',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPathRoute = AuthPathRouteImport.update({
  id: '/auth/$path',
  path: '/auth/$path',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStacksRedeployRoute = ApiStacksRedeployRouteImport.update({
  id: '/api/stacks/redeploy',
  path: '/api/stacks/redeploy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/$path': typeof AuthPathRoute
  '/settings/$path': typeof SettingsPathRoute
  '/stacks/$name': typeof StacksNameRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/stacks/redeploy': typeof ApiStacksRedeployRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/$path': typeof AuthPathRoute
  '/settings/$path': typeof SettingsPathRoute
  '/stacks/$name': typeof StacksNameRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/stacks/redeploy': typeof ApiStacksRedeployRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/$path': typeof AuthPathRoute
  '/settings/$path': typeof SettingsPathRoute
  '/stacks/$name': typeof StacksNameRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/stacks/redeploy': typeof ApiStacksRedeployRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/$path'
    | '/settings/$path'
    | '/stacks/$name'
    | '/api/auth/$'
    | '/api/stacks/redeploy'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/$path'
    | '/settings/$path'
    | '/stacks/$name'
    | '/api/auth/$'
    | '/api/stacks/redeploy'
  id:
    | '__root__'
    | '/'
    | '/auth/$path'
    | '/settings/$path'
    | '/stacks/$name'
    | '/api/auth/$'
    | '/api/stacks/redeploy'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthPathRoute: typeof AuthPathRoute
  SettingsPathRoute: typeof SettingsPathRoute
  StacksNameRoute: typeof StacksNameRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiStacksRedeployRoute: typeof ApiStacksRedeployRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stacks/$name': {
      id: '/stacks/$name'
      path: '/stacks/$name'
      fullPath: '/stacks/$name'
      preLoaderRoute: typeof StacksNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/$path': {
      id: '/settings/$path'
      path: '/settings/$path'
      fullPath: '/settings/$path'
      preLoaderRoute: typeof SettingsPathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/$path': {
      id: '/auth/$path'
      path: '/auth/$path'
      fullPath: '/auth/$path'
      preLoaderRoute: typeof AuthPathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stacks/redeploy': {
      id: '/api/stacks/redeploy'
      path: '/api/stacks/redeploy'
      fullPath: '/api/stacks/redeploy'
      preLoaderRoute: typeof ApiStacksRedeployRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthPathRoute: AuthPathRoute,
  SettingsPathRoute: SettingsPathRoute,
  StacksNameRoute: StacksNameRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiStacksRedeployRoute: ApiStacksRedeployRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
