/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VolumesRouteImport } from './routes/volumes'
import { Route as NetworksRouteImport } from './routes/networks'
import { Route as ImagesRouteImport } from './routes/images'
import { Route as ContainersRouteImport } from './routes/containers'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StacksNameRouteImport } from './routes/stacks.$name'
import { Route as SettingsPathRouteImport } from './routes/settings/$path'
import { Route as AuthPathRouteImport } from './routes/auth/$path'
import { Route as ApiInfoRouteImport } from './routes/api/info'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiStacksIndexRouteImport } from './routes/api/stacks/index'
import { Route as ApiWsLogsRouteImport } from './routes/api/ws/logs'
import { Route as ApiWsExecRouteImport } from './routes/api/ws/exec'
import { Route as ApiStacksRedeployRouteImport } from './routes/api/stacks/redeploy'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const VolumesRoute = VolumesRouteImport.update({
  id: '/volumes',
  path: '/volumes',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworksRoute = NetworksRouteImport.update({
  id: '/networks',
  path: '/networks',
  getParentRoute: () => rootRouteImport,
} as any)
const ImagesRoute = ImagesRouteImport.update({
  id: '/images',
  path: '/images',
  getParentRoute: () => rootRouteImport,
} as any)
const ContainersRoute = ContainersRouteImport.update({
  id: '/containers',
  path: '/containers',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StacksNameRoute = StacksNameRouteImport.update({
  id: '/stacks/$name',
  path: '/stacks/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsPathRoute = SettingsPathRouteImport.update({
  id: '/settings/$path',
  path: '/settings/$path',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPathRoute = AuthPathRouteImport.update({
  id: '/auth/$path',
  path: '/auth/$path',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInfoRoute = ApiInfoRouteImport.update({
  id: '/api/info',
  path: '/api/info',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStacksIndexRoute = ApiStacksIndexRouteImport.update({
  id: '/api/stacks/',
  path: '/api/stacks/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWsLogsRoute = ApiWsLogsRouteImport.update({
  id: '/api/ws/logs',
  path: '/api/ws/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWsExecRoute = ApiWsExecRouteImport.update({
  id: '/api/ws/exec',
  path: '/api/ws/exec',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStacksRedeployRoute = ApiStacksRedeployRouteImport.update({
  id: '/api/stacks/redeploy',
  path: '/api/stacks/redeploy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/containers': typeof ContainersRoute
  '/images': typeof ImagesRoute
  '/networks': typeof NetworksRoute
  '/volumes': typeof VolumesRoute
  '/api/health': typeof ApiHealthRoute
  '/api/info': typeof ApiInfoRoute
  '/auth/$path': typeof AuthPathRoute
  '/settings/$path': typeof SettingsPathRoute
  '/stacks/$name': typeof StacksNameRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/stacks/redeploy': typeof ApiStacksRedeployRoute
  '/api/ws/exec': typeof ApiWsExecRoute
  '/api/ws/logs': typeof ApiWsLogsRoute
  '/api/stacks/': typeof ApiStacksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/containers': typeof ContainersRoute
  '/images': typeof ImagesRoute
  '/networks': typeof NetworksRoute
  '/volumes': typeof VolumesRoute
  '/api/health': typeof ApiHealthRoute
  '/api/info': typeof ApiInfoRoute
  '/auth/$path': typeof AuthPathRoute
  '/settings/$path': typeof SettingsPathRoute
  '/stacks/$name': typeof StacksNameRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/stacks/redeploy': typeof ApiStacksRedeployRoute
  '/api/ws/exec': typeof ApiWsExecRoute
  '/api/ws/logs': typeof ApiWsLogsRoute
  '/api/stacks': typeof ApiStacksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/containers': typeof ContainersRoute
  '/images': typeof ImagesRoute
  '/networks': typeof NetworksRoute
  '/volumes': typeof VolumesRoute
  '/api/health': typeof ApiHealthRoute
  '/api/info': typeof ApiInfoRoute
  '/auth/$path': typeof AuthPathRoute
  '/settings/$path': typeof SettingsPathRoute
  '/stacks/$name': typeof StacksNameRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/stacks/redeploy': typeof ApiStacksRedeployRoute
  '/api/ws/exec': typeof ApiWsExecRoute
  '/api/ws/logs': typeof ApiWsLogsRoute
  '/api/stacks/': typeof ApiStacksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/containers'
    | '/images'
    | '/networks'
    | '/volumes'
    | '/api/health'
    | '/api/info'
    | '/auth/$path'
    | '/settings/$path'
    | '/stacks/$name'
    | '/api/auth/$'
    | '/api/stacks/redeploy'
    | '/api/ws/exec'
    | '/api/ws/logs'
    | '/api/stacks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/containers'
    | '/images'
    | '/networks'
    | '/volumes'
    | '/api/health'
    | '/api/info'
    | '/auth/$path'
    | '/settings/$path'
    | '/stacks/$name'
    | '/api/auth/$'
    | '/api/stacks/redeploy'
    | '/api/ws/exec'
    | '/api/ws/logs'
    | '/api/stacks'
  id:
    | '__root__'
    | '/'
    | '/containers'
    | '/images'
    | '/networks'
    | '/volumes'
    | '/api/health'
    | '/api/info'
    | '/auth/$path'
    | '/settings/$path'
    | '/stacks/$name'
    | '/api/auth/$'
    | '/api/stacks/redeploy'
    | '/api/ws/exec'
    | '/api/ws/logs'
    | '/api/stacks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContainersRoute: typeof ContainersRoute
  ImagesRoute: typeof ImagesRoute
  NetworksRoute: typeof NetworksRoute
  VolumesRoute: typeof VolumesRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiInfoRoute: typeof ApiInfoRoute
  AuthPathRoute: typeof AuthPathRoute
  SettingsPathRoute: typeof SettingsPathRoute
  StacksNameRoute: typeof StacksNameRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiStacksRedeployRoute: typeof ApiStacksRedeployRoute
  ApiWsExecRoute: typeof ApiWsExecRoute
  ApiWsLogsRoute: typeof ApiWsLogsRoute
  ApiStacksIndexRoute: typeof ApiStacksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/volumes': {
      id: '/volumes'
      path: '/volumes'
      fullPath: '/volumes'
      preLoaderRoute: typeof VolumesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/networks': {
      id: '/networks'
      path: '/networks'
      fullPath: '/networks'
      preLoaderRoute: typeof NetworksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/images': {
      id: '/images'
      path: '/images'
      fullPath: '/images'
      preLoaderRoute: typeof ImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/containers': {
      id: '/containers'
      path: '/containers'
      fullPath: '/containers'
      preLoaderRoute: typeof ContainersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stacks/$name': {
      id: '/stacks/$name'
      path: '/stacks/$name'
      fullPath: '/stacks/$name'
      preLoaderRoute: typeof StacksNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/$path': {
      id: '/settings/$path'
      path: '/settings/$path'
      fullPath: '/settings/$path'
      preLoaderRoute: typeof SettingsPathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/$path': {
      id: '/auth/$path'
      path: '/auth/$path'
      fullPath: '/auth/$path'
      preLoaderRoute: typeof AuthPathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/info': {
      id: '/api/info'
      path: '/api/info'
      fullPath: '/api/info'
      preLoaderRoute: typeof ApiInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stacks/': {
      id: '/api/stacks/'
      path: '/api/stacks'
      fullPath: '/api/stacks/'
      preLoaderRoute: typeof ApiStacksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ws/logs': {
      id: '/api/ws/logs'
      path: '/api/ws/logs'
      fullPath: '/api/ws/logs'
      preLoaderRoute: typeof ApiWsLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ws/exec': {
      id: '/api/ws/exec'
      path: '/api/ws/exec'
      fullPath: '/api/ws/exec'
      preLoaderRoute: typeof ApiWsExecRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stacks/redeploy': {
      id: '/api/stacks/redeploy'
      path: '/api/stacks/redeploy'
      fullPath: '/api/stacks/redeploy'
      preLoaderRoute: typeof ApiStacksRedeployRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContainersRoute: ContainersRoute,
  ImagesRoute: ImagesRoute,
  NetworksRoute: NetworksRoute,
  VolumesRoute: VolumesRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiInfoRoute: ApiInfoRoute,
  AuthPathRoute: AuthPathRoute,
  SettingsPathRoute: SettingsPathRoute,
  StacksNameRoute: StacksNameRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiStacksRedeployRoute: ApiStacksRedeployRoute,
  ApiWsExecRoute: ApiWsExecRoute,
  ApiWsLogsRoute: ApiWsLogsRoute,
  ApiStacksIndexRoute: ApiStacksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
